apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlruns-pvc
spec:
  accessModes:
    - ReadWriteOnce # This is standard for single-node clusters like Minikube
  resources:
    requests:
      storage: 1Gi # Allocate 1 Gigabyte for MLflow runs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Allocate 1 Gigabyte for sensor data, models, etc.